#!/usr/bin/env python3
"""Build a raw-code pretraining source from codeparrot/github-code-clean.

    python scripts/prepare_github_code.py --shards 0-29

github-code-clean (https://huggingface.co/datasets/codeparrot/github-code-clean)
is ~115M deduplicated GitHub files in 880 parquet shards (~356MB each), every
file tagged with its repo's license. This keeps only Python, C++, Rust and
Shell files under permissive licenses, drops obvious junk (generated files,
minified/data blobs, very long lines), removes exact duplicates, and stops each
language at a GPT-2 token cap.

Output is data/sources/github_<language>/github_code_clean.jsonl (python,
cpp, rust, shell), one record per file,
ready for scripts/build_mix.py. Shards are cached by huggingface_hub; rerunning
with the same arguments gives the same files.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import pyarrow.parquet as pq
import tiktoken
from huggingface_hub import hf_hub_download

REPO = "codeparrot/github-code-clean"
PERMISSIVE = {"mit", "apache-2.0", "bsd-3-clause", "bsd-2-clause", "isc", "unlicense", "cc0-1.0"}
# GPT-2 tokens per language. C++ is plentiful, Rust and Shell are scarce.
CAPS = {"Python": 300_000_000, "C++": 150_000_000, "Rust": 50_000_000, "Shell": 30_000_000}
GENERATED = ("auto-generated", "autogenerated", "automatically generated", "generated by", "do not edit")


def shard_range(spec: str) -> list[int]:
    lo, _, hi = spec.partition("-")
    return list(range(int(lo), int(hi or lo) + 1))


def looks_ok(code: str) -> bool:
    """StarCoder/Codex-style heuristics: skip generated files and data blobs."""
    if not 200 <= len(code) <= 100_000:
        return False
    lines = code.splitlines()
    if max(map(len, lines)) > 1000 or len(code) / len(lines) > 100:
        return False
    if sum(c.isalnum() for c in code) / len(code) < 0.25:
        return False
    head = "\n".join(lines[:10]).lower()
    return not any(marker in head for marker in GENERATED)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--shards", default="0-29", help="shard range, e.g. 0-29")
    parser.add_argument("--sources-dir", type=Path,
                        default=Path(__file__).resolve().parent.parent / "data" / "sources")
    args = parser.parse_args()

    enc = tiktoken.get_encoding("gpt2")
    outs = {}
    for lang in CAPS:
        out_dir = args.sources_dir / f"github_{lang.lower().replace('+', 'p')}"
        out_dir.mkdir(parents=True, exist_ok=True)
        outs[lang] = (out_dir / "github_code_clean.jsonl").open("w", encoding="utf-8")
    tokens = dict.fromkeys(CAPS, 0)
    files = dict.fromkeys(CAPS, 0)
    seen: set[bytes] = set()
    dropped = 0

    for shard in shard_range(args.shards):
        if all(tokens[lang] >= CAPS[lang] for lang in CAPS):
            break
        path = hf_hub_download(REPO, f"data/train-{shard:05d}-of-00880.parquet", repo_type="dataset")
        table = pq.read_table(path, columns=["code", "repo_name", "path", "language", "license"])
        for row in table.to_pylist():
            lang = row["language"]
            if lang not in CAPS or tokens[lang] >= CAPS[lang] or row["license"] not in PERMISSIVE:
                continue
            code = row["code"]
            digest = hashlib.sha1(code.encode()).digest()
            if digest in seen or not looks_ok(code):
                dropped += 1
                continue
            seen.add(digest)
            record = {
                "id": f"github_code/{row['repo_name']}/{row['path']}",
                "text": code,
                "metadata": {"language": lang, "repo": row["repo_name"], "path": row["path"],
                             "license": row["license"]},
            }
            outs[lang].write(json.dumps(record, ensure_ascii=False) + "\n")
            tokens[lang] += len(enc.encode_ordinary(code))
            files[lang] += 1
        print(f"shard {shard}: " + ", ".join(f"{l} {tokens[l] / 1e6:.0f}M" for l in CAPS)
              + f", dropped {dropped:,}", flush=True)

    for f in outs.values():
        f.close()
    for lang in CAPS:
        print(f"{lang:7} {files[lang]:9,} files {tokens[lang]:13,} tokens")


if __name__ == "__main__":
    main()
