#!/usr/bin/env python3
"""Build the smoltalk source: rewriting and constraint-following conversations.

    python scripts/prepare_smoltalk.py

From SmolTalk (https://huggingface.co/datasets/HuggingFaceTB/smoltalk), only the
two subsets that are Apache-2.0 *and* not generated by Llama:

- smol-rewrite: rewrite a pasted text (friendlier, more formal, more concise).
- smol-constraints: follow explicit instructions ("at least 3 sentences",
  "include the word X", "end with P.S.").

Both were generated with Qwen2.5-72B-Instruct, whose license asks that a model
trained on its outputs say "Built with Qwen" in its documentation if the model
is distributed. The Llama-generated subsets (smol-magpie-ultra,
everyday-conversations) are skipped: Llama 3.1's license would require the
model's name to start with "Llama". smol-summarize is skipped too (CNN/DailyMail
articles).

The full subsets (~87K conversations, ~23M tokens) would swamp the other chat
sources, so a hash-selected sample is kept (--rewrite / --constraints); rerunning
with the same arguments gives the same records.

Output is data/sources/smoltalk/<subset>.jsonl, chat records for build_mix.py.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import pyarrow.parquet as pq
import tiktoken
from huggingface_hub import hf_hub_download

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from chat_template import render

REPO = "HuggingFaceTB/smoltalk"
REVISION = "5feaf2fd3ffca7c237fc38d1861bc30365d48ffa"
MAX_TOKENS = 1000          # context is 1024


def digest(messages) -> str:
    return hashlib.sha256(json.dumps(messages, sort_keys=True).encode()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--rewrite", type=int, default=12_000, help="smol-rewrite conversations to keep")
    parser.add_argument("--constraints", type=int, default=8_000, help="smol-constraints conversations to keep")
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parent.parent / "data" / "sources" / "smoltalk")
    args = parser.parse_args()
    enc = tiktoken.get_encoding("gpt2")
    args.output_dir.mkdir(parents=True, exist_ok=True)

    provenance = []
    for subset, keep in (("smol-rewrite", args.rewrite), ("smol-constraints", args.constraints)):
        path = hf_hub_download(REPO, f"data/{subset}/train-00000-of-00001.parquet",
                               repo_type="dataset", revision=REVISION)
        rows = pq.read_table(path).column("messages").to_pylist()
        # Lowest hashes first: a stable, spread-out sample.
        candidates = sorted((digest(m), m) for m in rows)
        records, too_long, tokens, seen = [], 0, 0, set()
        for h, messages in candidates:
            if len(records) == keep:
                break
            if h in seen:          # the upstream subsets contain exact duplicates
                continue
            seen.add(h)
            turns = [{"role": m["role"], "content": m["content"].strip()} for m in messages]
            n = len(enc.encode_ordinary(render(turns)))
            if n > MAX_TOKENS:
                too_long += 1
                continue
            tokens += n
            records.append({"id": f"smoltalk/{subset}/{h[:16]}", "messages": turns,
                            "metadata": {"subset": subset, "license": "Apache-2.0",
                                         "origin": "HuggingFaceTB/smoltalk (Qwen2.5-72B-Instruct generated)"}})
        with (args.output_dir / f"{subset}.jsonl").open("w", encoding="utf-8") as f:
            for r in records:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")
        provenance.append({"subset": subset, "available": len(rows), "kept": len(records),
                           "too_long": too_long, "tokens": tokens})
        print(f"{subset:<18} kept {len(records):,} of {len(rows):,}  {tokens:,} tokens  ({too_long} too long)")

    (args.output_dir / "provenance.json").write_text(json.dumps(
        {"description": "SmolTalk smol-rewrite + smol-constraints samples.",
         "repository": f"https://huggingface.co/datasets/{REPO}", "revision": REVISION,
         "license": "Apache-2.0; generated with Qwen2.5-72B-Instruct (Qwen license: "
                    "'Built with Qwen' attribution if a trained model is distributed)",
         "subsets": provenance}, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
